### ISSUE TITLE
Pre-trained visual encoder, 4M pretraining?

### ISSUE THREAD

**Issue by m-bain** [microsoft/BridgeTower#1]
HI thanks for this valuable work, its a good insight into fusing vision and text and impressive results :).

Regarding the initialisation of the visual encoder, pretrained CLIP is used for the visual encoder, trained on 400M images?

It's somewhat confusing because in the table it states 4M images used for #pretraining.

**Comment by Moymix** [comment]
Thanks for your question!
The "4M" pretraining data means we pretrain our proposed Bridge-Tower in 4M data. We follow the common practice in VL pretraining field without including the pretrained visual backbone. Pls refer to [METER paper](https://openaccess.thecvf.com/content/CVPR2022/html/Dou_An_Empirical_Study_of_Training_End-to-End_Vision-and-Language_Transformers_CVPR_2022_paper.html).
But anyway, this is a good suggestion, as we will make it more clear in our next version.

**Comment by jotaf98** [comment]
Hi, I'm not sure that the METER paper provides any evidence in that regard. In their "Pretraining" section, they claim to only use Adam with these 4 datasets (<4M images), and there's no mention anywhere of any other kind of pretraining in their visual backbones.

Even if they did, it wouldn't be a good precedent to follow, as it would render all the statements about pretraining false (since more than 4M images were used before the training stage).

**Comment by LooperXX** [comment]
Hi, @m-bain and @jotaf98. Thanks for your suggestions!
1. About "Pre-trained visual encoder, 4M pretraining?": The statistics of the pre-training datasets are shown in [METER Paper](https://arxiv.org/abs/2111.02387) Appendix A Table 11 and [Bridge-Tower Paper](https://arxiv.org/abs/2206.08657) Appendix A.5 Table 9. It is a common practice to adopt the pre-trained visual and/or textual backbone and then continue to pre-train with the 4M images. Almost all the baselines (except SimVLM) in Table 4 of our paper adopt the pre-trained visual and/or textual backbone. The pre-trained visual and/or textual backbones used by these baselines are various. Hence, for brevity, VL papers often do not show the data used by the pre-trained visual and/or textual backbone in the result tables. You can check these details in VL papers. BTW, as confusing as it may seem, we will make it more clear in our next version.

2. About "METER Pre-training": In [Section 4.5](https://arxiv.org/abs/2111.02387), METER adopts the pre-trained CLIP-ViT(or Swin Transformer) and RoBERTa as their visual/textual backbone, then pre-trains their model with the 4M data. As shown in [Section 4.1(Ours)](https://arxiv.org/abs/2206.08657), we also use CLIP-ViT and RoBERTa as backbones and then pre-train them with the same 4 datasets. The comparison between METER and Bridge-Tower is fair and proves bridges can help Vision-Language Representation Learning.

**Comment by m-bain** [comment]
Just to respond to #1:
- ALBEF uses DieT visual backbone trained on imagenet
- VLMO [77] uses SSL image-only initialisation.

Some other works extract FRCNN region features, so yes the backbones are various.

But comparing to these works (and giving them all the same 4M column) and pretraining your visual encoder on 400M image-text pretraining backbone is not a fair comparison. It's possible your SOTA performance is due to CLIP backbone (you can see this from the big boost METER get from swin->clip), since you don't provide any ablation on this there is no way to tell. E.g. what would 4M ALBEF performance if they also use clip initialization?

A helpful fix would be to add a column on "visual backbone" like we did in our frozen in time paper.
